# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - 'develop'
      - 'master'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # `action/setup-node@v2` will create an .npmrc file referencing $NODE_AUTH_TOKEN
      # So we can set $NODE_AUTH_TOKEN with right permission when we publish or install npm packages
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: './.github/actions/get_runner_env_version'
        id: get-runner-env-version
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules/
          key: ${{ steps.get-runner-env-version.outputs.os }}-node${{ steps.get-runner-env-version.outputs.node }}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install packages without updating lock file
        run: yarn --frozen-lockfile
      - name: Build Storybook
        run: yarn build-storybook
      # Start of push storybook to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Extract branch name
        shell: bash
        run: run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Copy files to the test website with the AWS CLI
        if: extract_branch == develop
        run: |
          aws s3 sync ./storybook-static s3://frontend-storybook-bucket/develop/
      # End of push storybook to AWS
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: master|develop
          skip: nostorybook/**
          exitZeroOnChanges: true
          storybookBuildDir: storybook-static
